version: '3.1'

services:
  db:
    image: mysql:8.1.0
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 2020
      MYSQL_DATABASE: consultorio

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  dbbase: